- 
  name: Install chrony on all servers
  hosts: all_targets
  tasks:
   - name: install chrony
     yum:
        name: chrony
        state: present
   - name: start Chrony Service
     service:
         name: chronyd
         state: started
         enabled: yes 
