- 
  name: Execute Date on all servers 
  hosts: all_targets
  tasks: 
    - 
      name: Show date and all servers
      command: date

    - 
      name: Show contents of /etc/hosts
      command: cat /etc/hosts
 
- name: Excute something on target1
  hosts: target1
  tasks: 
    -
      name: show present working directory 
      command: pwd chdir=/
